"""Generate src/app/templates_inline.py from src/app/templates/.

Why: on Cloudflare Workers we cannot rely on the worker's filesystem for
Jinja templates, so every template is also embedded as a string. The Flask app
uses ChoiceLoader([FileSystemLoader, DictLoader]) - the filesystem wins when
available (local dev), the embedded copy guarantees production rendering.

Re-run this script (and commit the output) whenever a template changes:

    python scripts/build_inline_templates.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(ROOT, "src", "app", "templates")
OUT_PATH = os.path.join(ROOT, "src", "app", "templates_inline.py")


def collect() -> dict:
    found = {}
    for dirpath, _dirnames, filenames in os.walk(TEMPLATES_DIR):
        for filename in sorted(filenames):
            full = os.path.join(dirpath, filename)
            key = os.path.relpath(full, TEMPLATES_DIR).replace(os.sep, "/")
            with open(full, encoding="utf-8") as handle:
                found[key] = handle.read()
    return dict(sorted(found.items()))


def main() -> None:
    templates = collect()
    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write(
            '"""Embedded Jinja templates (Workers filesystem fallback).\n\n'
            "GENERATED by scripts/build_inline_templates.py - do not hand-edit.\n"
            '"""\n\n# ruff: noqa\n\nTEMPLATES = {\n'
        )
        for key, content in templates.items():
            handle.write(f"    {key!r}: (\n        {content!r}\n    ),\n")
        handle.write("}\n")
    print(f"wrote {OUT_PATH} with {len(templates)} templates")


if __name__ == "__main__":
    main()
