"""Append demo leaderboard rows to db_init.sql. Run AFTER seed_words.py.

Usage:
    python scripts/seed_words.py
    python scripts/seed_demo.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# (player_name, score, difficulty, result, category, created_at UTC)
# Note the intentional tie at 240 points (earliest submission ranks first).
DEMOS = [
    ("Mahnoor", 410, "Hard", "won", "Science", "2026-09-02T09:12:00.000000Z"),
    ("Bilal", 350, "Hard", "won", "General", "2026-09-03T14:40:00.000000Z"),
    ("Fatima", 305, "Medium", "won", "Animals", "2026-09-04T11:05:00.000000Z"),
    ("Daniyal", 280, "Medium", "won", "Sports", "2026-09-05T16:22:00.000000Z"),
    ("Ayesha", 240, "Medium", "won", "Geography", "2026-09-06T10:00:00.000000Z"),
    ("Kamran", 240, "Easy", "won", "General", "2026-09-07T10:00:00.000000Z"),
    ("Hina", 215, "Medium", "won", "Daily", "2026-09-08T08:31:00.000000Z"),
    ("Imran", 190, "Easy", "won", "Animals", "2026-09-09T12:45:00.000000Z"),
    ("Zara", 165, "Easy", "won", "General", "2026-09-09T18:02:00.000000Z"),
    ("Usman", 120, "Easy", "won", "Sports", "2026-09-10T09:20:00.000000Z"),
    ("Sana", 95, "Medium", "won", "Science", "2026-09-11T15:11:00.000000Z"),
    ("Faisal", 60, "Hard", "won", "Geography", "2026-09-12T20:44:00.000000Z"),
    ("Guest", 0, "Hard", "lost", "General", "2026-09-12T21:00:00.000000Z"),
]


def main() -> None:
    out_path = os.path.join(ROOT, "db_init.sql")
    if not os.path.isfile(out_path):
        raise SystemExit("db_init.sql not found. Run scripts/seed_words.py first.")
    with open(out_path, "a", encoding="utf-8") as handle:
        handle.write("-- Demo leaderboard rows (generated by scripts/seed_demo.py).\n")
        values = ",\n  ".join(
            f"('{name}', {score}, '{difficulty}', '{result}', '{category}', NULL, '{created}')"
            for name, score, difficulty, result, category, created in DEMOS
        )
        handle.write(
            "INSERT OR IGNORE INTO scores (player_name, score, difficulty, result,"
            " category, user_id, created_at) VALUES\n  " + values + ";\n"
        )
    print(f"appended {len(DEMOS)} demo scores to {out_path}")


if __name__ == "__main__":
    main()
