"""Cloudflare Workers entrypoint (Python runtime only).

Serves the Flask app through the official WSGI adapter from
``workers-runtime-sdk``, mirroring the official flask-todo example at
https://github.com/cloudflare/python-workers-examples::

    Default = wsgi.entrypoint(app)

Self-contained bundle: the pinned dependency closure is vendored as
pure-Python source in ``src/python_modules/`` (generated by
``scripts/vendor_python_modules.py`` from ``docs/requirements-pinned.txt``),
because Workers Builds runs ``pip install .`` + ``wrangler versions upload``,
which never executes ``pywrangler sync`` -- so third-party packages would
otherwise be missing from the uploaded bundle. wrangler attaches every file
under ``src/`` (moduleRoot), and the vendored directory is put on ``sys.path``
first so the vendored ``workers`` package (with ``wsgi``) shadows the older
copy baked into the runtime image.

The D1 binding is exposed to Flask routes as
``request.environ["workers.env"].DB`` and is consumed in src/app/db.py.

No build step is required: any deploy of this commit uploads src/ as-is.
``pywrangler sync`` remains useful for local ``wrangler dev`` iterations.
"""

import os
import sys

_SRC_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _SRC_DIR)
sys.path.insert(0, os.path.join(_SRC_DIR, "python_modules"))

from workers import wsgi  # noqa: E402  (vendored in src/python_modules)

from app import create_app  # noqa: E402

Default = wsgi.entrypoint(create_app())
